[package]
name = "sui-test-validator"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.58", features = ["backtrace"] }
clap = { version = "3.1.17", features = ["derive"] }
schemars = "0.8.10"
serde = "1.0.140"
workspace-hack = { path = "../workspace-hack"}
nexlint = { git = "https://github.com/nextest-rs/nexlint.git", rev = "bff03c566c9e22b1f4e67f516d0fd592a5a88f20" }
nexlint-lints = { git = "https://github.com/nextest-rs/nexlint.git", rev = "bff03c566c9e22b1f4e67f516d0fd592a5a88f20" }
pretty_assertions = "1.2.0"
serde_json = "1.0.80"
tokio = { version = "1.20.1", features = ["full"] }
hyper = { version = "0.14.20", features = ["full"] }
camino = "1.0.9"

sui = { path = "../sui" }
sui-json-rpc = { path = "../sui-json-rpc" }
sui-json-rpc-types = { path = "../sui-json-rpc-types" }
sui-json = { path = "../sui-json" }
sui-types = { path = "../sui-types" }
sui-test-data = { path = "../sui-test-data" }
sui-config = { path = "../sui-config" }
test-utils = { path = "../test-utils" }

move-package = { git = "https://github.com/move-language/move", rev = "79071528524f08b12e9abb84c1094d8e976aa17a" }
